export const CONFIG = {
    LARGEUR_FENETRE: 800,
    TAILLE_CASE: 40,
    POURCENTAGE_OBSTACLES: 0.20,
    VITESSE: 0.5, 
    FPS_BASE: 60,
    COULEURS: {
        BG: "#f2f2f2",
        GRAY: "rgba(200, 200, 200, 1)",
        GRINCH_CERCLE: "rgba(50, 255, 50, 0.4)",
        CADEAU_CERCLE: "rgba(255, 255, 50, 0.4)",
        DOREE_CERCLE: "rgba(255, 215, 0, 0.6)",
        MENU_BG: "#0f0f23",
        TEXTE_OR: "#FFD700"
    },
    DUREE_VIE_DOREE: 5000,
    POINTS_NORMAL: 1,
    POINTS_DOREE: 5,
    ACCELERATION: 1,
    DIMENSIONS_GRINCH: [200, 100],
    DIMENSIONS_CORPS: [180, 90],
    DECALAGE_VISUEL_Y: 10,
    DECALAGE_CORPS_Y: 10,
    TAILLE_HITBOX_GRINCH: 20,
    MARGE_TOLERANCE_MAISON: -15
};

// Calculs dérivés
CONFIG.NB_COLONNES = CONFIG.LARGEUR_FENETRE / CONFIG.TAILLE_CASE;
CONFIG.NB_LIGNES = CONFIG.LARGEUR_FENETRE / CONFIG.TAILLE_CASE;
CONFIG.GAP_QUEUE = CONFIG.TAILLE_CASE / CONFIG.VITESSE;